---
- hosts: nodes
  gather_facts: no
  become: true
  tasks:
  - name: check that python is at latest version
    raw: apk -U add python3
  - name: check that apache is at latest version
    apk:
      name: apache2 
      state: latest
  - name: copy index.html into its place
    template:
      src: index.html
      dest: /var/www/localhost/htdocs/index.html
    notify:
    - restart apache
  - name: check that apache is running
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
